version: '3.9'

services:
  mongodb-fids:
    image: mongo:6.0
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ~/.docker-volumes/mongo/data:/data/db
  fidsbackend.api:
    hostname: fidsbackend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: ${DOCKER_REGISTRY-}fidsbackendapi
    build:
      context: .
      dockerfile: FIDS.Backend/Dockerfile
    ports:
      - 5000:5000
  fidsdepartureclient:
    environment:
      - BACKEND_URL=http://fidsbackend:5000
    image: ${DOCKER_REGISTRY-}fidsdepartureclient
    build:
      context: .
      dockerfile: FIDS.DepartureClient/Dockerfile
  fidsarrivalclient:
    environment:
      - BACKEND_URL=http://fidsbackend:5000
    image: ${DOCKER_REGISTRY-}fidsarrivallient
    build:
      context: .
      dockerfile: FIDS.ArrivalClient/Dockerfile