version: '3.4'

services:
  fly:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  flyplusjourneycontentenricher:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  flyrejser:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  workerfids:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
