version: "3.9"
services:
  Mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=yourStrong(!)Password
  MyBackend:
    image: fly:dev
    ports:
        - "80:80"
    environment:
        - Ip=Mssql
