name: Build and Push Docker Image

on:
  push:
    branches:
      - Demo-Blazor
  pull_request:
    branches:
      - Demo-Blazor

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: fids-backend/fidsrepo:latest

   tests:
      name: Run unit tests for FIDS.Backend
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - run: dotnet test

